---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: hope
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: hope-nginx
    spec:
      containers:
      - name: hope-nginx
        image: nginx
        ports:
        - containerPort: 80	
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  namespace: hope
spec:
  ports:
  - port: 80
    nodePort: 30001
    targetPort: 80
  type: NodePort
  selector:
    app: hope-nginx
